  
sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd RestWithASPNETUdemy
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "xxx.yyy" | docker login --username "jaderfck" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy:latest jaderfck/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-udemy-db:latest jaderfck/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
    docker push jaderfck/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push jaderfck/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
  on:
    branch: main
notifications:
  email: false
